language:
  node_js
node_js: lts/*
before_install:
  - npm install -g codecov
  - composer self-update
  - composer install --no-interaction --optimize-autoloader
script:
  - set e
  - npm test
  - codecov