codecov:
    require_ci_to_pass: yes

fixes:
    - './index.js::index.js'
    - 'lib/::./lib'
    - 'lib/time.js'::./lib/time.js'
    - 'lib/getName.js'::./getName.d.ts'
    - 'lib/slash.js::./lib/slash.js'

coverage:
    precision: 2
    round: down
    range: '70...100'
    threshold: 20%

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

comment:
    layout: 'reach,diff,flags,files,footer'
    behavior: default
    require_changes: no
